export enum WorkerCommands {
  // transaction service / parsing transaction
  FLOW_PARSING,
  MEDIA_REPORT_PARSING,
  TRANSACTION_SERVICE_TRNS,
  TRANSACTION_SERVICE_DTMF,
  TRANSACTION_SERVICE_QOS,
  TRANSACTION_SERVICE_LOG,
  TRANSACTION_SERVICE_FULL,
  TRANSACTION_SERVICE_ONE_WAY_AUDIO,
  // clickhouse chart widget
  CLICKHOUSE_PARSE_DATA,
  CLICKHOUSE_PREPARE_RENDER_DATA
}
